- name: Build and package (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run dist:win -- --publish never
      
    - name: Build and package (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run dist:mac -- --publish never
      
    - name: Build and package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run dist:linux -- --publish never
